// this file was generated by better-cmake
// psp-elfdump v0.9.0

#define psp-elfdump_NAME "psp-elfdump"
#define psp-elfdump_AUTHOR "DaemonTsun"
#define psp-elfdump_VERSION "0.9.0"
#define psp-elfdump_VERSION_MAJOR 0
#define psp-elfdump_VERSION_MINOR 9
#define psp-elfdump_VERSION_PATCH 0
