// this file was generated by better-cmake
// psp-module-format v1.0.0

#define psp_module_format_NAME "psp-module-format"
#define psp_module_format_AUTHOR "DaemonTsun"
#define psp_module_format_VERSION "1.0.0"
#define psp_module_format_VERSION_MAJOR 1
#define psp_module_format_VERSION_MINOR 0
#define psp_module_format_VERSION_PATCH 0
