// this file was generated by better-cmake
// allegrex v1.0.3

#define allegrex_NAME "allegrex"
#define allegrex_AUTHOR "DaemonTsun"
#define allegrex_VERSION "1.0.3"
#define allegrex_VERSION_MAJOR 1
#define allegrex_VERSION_MINOR 0
#define allegrex_VERSION_PATCH 3
