
#include "allegrex/internal/psp_module_function_argument_defs.hpp"

const char *_get_psp_function_arg_name(psp_function_arg_t arg)
{
    // TODO: optimize
    switch (arg)
    {
    case WC_(ARG_NONE):           return "";
    case WC_(ARG_VOID):           return "void";
    case WC_(ARG_U32):            return "u32";
    case WC_(ARG_S32):            return "s32";
    case WC_(ARG_FLOAT):          return "float";
    case WC_(ARG_U64):            return "u64";
    case WC_(ARG_S64):            return "s64";
    case WC_(ARG_DOUBLE):         return "double";
    case WC_(ARG_CONST_CHAR_PTR): return "const char *";
    case WC_(ARG_PTR):            return "ptr";
    case WC_(ARG_U32_PTR):        return "u32 *";
    case WC_(ARG_S32_PTR):        return "s32 *";
    case WC_(ARG_U8):             return "u8";
    case WC_(ARG_U8_PTR):         return "u8 *";
    case WC_(ARG_CONST_U8_PTR):   return "const u8 *";
    case WC_(ARG_CHAR_PTR):       return "char *";
    case WC_(ARG_U16):            return "u16";
    case WC_(ARG_U16_PTR):        return "u16 *";
    case WC_(ARG_S16):            return "s16";
    case WC_(ARG_S16_PTR):        return "s16 *";
    case WC_(ARG_U64_PTR):        return "u64 *";
    case WC_(ARG_S64_PTR):        return "s64 *";
    case WC_(ARG_CONST_U64_PTR):  return "const u64 *";
    case WC_(ARG_U8_PTR_PTR):     return "u8 **";
    case WC_(ARG_S16_PTR_PTR):    return "s16 **";

    case WC_(ARG_VOID_PTR):       return "void *";
    case WC_(ARG_CONST_VOID_PTR): return "const void *";
    case WC_(ARG_VOID_PTR_PTR):   return "void **";

    case WC_(ARG_SceUID):         return "SceUID";
    case WC_(ARG_SceUID_PTR):     return "SceUID *";
    case WC_(ARG_SceSize):        return "SceSize";
    case WC_(ARG_SceUChar):       return "SceUChar";
    case WC_(ARG_SceUInt):        return "SceUInt";
    case WC_(ARG_SceUInt32):      return "SceUInt32";
    case WC_(ARG_SceUInt64):      return "SceUInt64";
    case WC_(ARG_SceUInt_PTR):    return "SceUInt *";
    case WC_(ARG_SceInt):         return "SceInt";
    case WC_(ARG_SceInt32):       return "SceInt32";
    case WC_(ARG_SceInt64):       return "SceInt64";
    case WC_(ARG_SceInt_PTR):     return "SceInt *";
    case WC_(ARG_SceInt64_PTR):   return "SceInt64 *";

    case WC_(ARG_SceMode):        return "SceMode";
    case WC_(ARG_SceOff):         return "SceOff";
    case WC_(ARG_SceIores):       return "SceIores";

    case WC_(ARG_SceLwMutexWorkarea_PTR):              return "SceLwMutexWorkarea *";
    case WC_(ARG_SceKernelEventFlagOptParam_PTR):      return "SceKernelEventFlagOptParam *";
    case WC_(ARG_SceKernelEventFlagInfo_PTR):          return "SceKernelEventFlagInfo *";
    case WC_(ARG_SceKernelSemaOptParam_PTR):           return "SceKernelSemaOptParam *";
    case WC_(ARG_SceKernelSemaInfo_PTR):               return "SceKernelSemaInfo *";
    case WC_(ARG_SceKernelThreadEntry):                return "SceKernelThreadEntry";
    case WC_(ARG_SceKernelThreadOptParam_PTR):         return "SceKernelThreadOptParam *";
    case WC_(ARG_SceKernelSysClock_PTR):               return "SceKernelSysClock *";
    case WC_(ARG_SceKernelThreadRunStatus_PTR):        return "SceKernelThreadRunStatus *";
    case WC_(ARG_SceKernelThreadInfo_PTR):             return "SceKernelThreadInfo *";
    case WC_(ARG_SceKernelIdListType):                 return "SceKernelIdListType";
    case WC_(ARG_PspDebugProfilerRegs_PTR):            return "PspDebugProfilerRegs *";
    case WC_(ARG_SceKernelSystemStatus_PTR):           return "SceKernelSystemStatus *";
    case WC_(ARG_SceKernelAlarmHandler):               return "SceKernelAlarmHandler";
    case WC_(ARG_SceKernelAlarmInfo_PTR):              return "SceKernelAlarmInfo *";
    case WC_(ARG_SceKernelThreadEventHandler):         return "SceKernelThreadEventHandler";
    case WC_(ARG_SceKernelThreadEventHandlerInfo_PTR): return "SceKernelThreadEventHandlerInfo *";
    case WC_(ARG_SceKernelCallbackFunction):           return "SceKernelCallbackFunction";
    case WC_(ARG_SceKernelCallbackInfo_PTR):           return "SceKernelCallbackInfo *";
    case WC_(ARG_SceKernelMbxOptParam_PTR):            return "SceKernelMbxOptParam *";
    case WC_(ARG_SceKernelMbxInfo_PTR):                return "SceKernelMbxInfo *";
    case WC_(ARG_SceKernelMppInfo_PTR):                return "SceKernelMppInfo *";
    case WC_(ARG_SceKernelVplOptParam_PTR):            return "SceKernelVplOptParam *";
    case WC_(ARG_SceKernelVplInfo_PTR):                return "SceKernelVplInfo *";
    case WC_(ARG_SceKernelFplOptParam_PTR):            return "SceKernelFplOptParam *";
    case WC_(ARG_SceKernelFplInfo_PTR):                return "SceKernelFplInfo *";
    case WC_(ARG_SceKernelVTimerOptParam_PTR):         return "SceKernelVTimerOptParam *";
    case WC_(ARG_SceKernelVTimerInfo_PTR):             return "SceKernelVTimerInfo *";
    case WC_(ARG_SceKernelVTimerHandler):              return "SceKernelVTimerHandler";
    case WC_(ARG_SceKernelVTimerHandlerWide):          return "SceKernelVTimerHandlerWide";
    case WC_(ARG_SceKernelTimeval_PTR):                return "SceKernelTimeval *";
    case WC_(ARG_timezone_PTR):                        return "timezone *";
    case WC_(ARG_clock_t):                             return "clock_t";
    case WC_(ARG_SceKernelLoadExecParam_PTR):          return "SceKernelLoadExecParam *";
    case WC_(ARG_SceKernelUtilsMd5Context_PTR):        return "SceKernelUtilsMd5Context *";
    case WC_(ARG_time_t):                              return "time_t";
    case WC_(ARG_time_t_PTR):                          return "time_t *";
    case WC_(ARG_SceKernelUtilsMt19937Context_PTR):    return "SceKernelUtilsMt19937Context *";
    case WC_(ARG_PspIntrHandlerOptionParam_PTR):       return "PspIntrHandlerOptionParam *";
    case WC_(ARG_SceIoDirent_PTR):                     return "SceIoDirent *";
    case WC_(ARG_SceIoStat_PTR):                       return "SceIoStat *";
    case WC_(ARG_SceKernelLMOption_PTR):               return "SceKernelLMOption *";
    case WC_(ARG_SceKernelSMOption_PTR):               return "SceKernelSMOption *";
    case WC_(ARG_SceKernelModuleInfo_PTR):             return "SceKernelModuleInfo *";
    case WC_(ARG_SceCtrlData_PTR):                     return "SceCtrlData *";
    case WC_(ARG_SceCtrlLatch_PTR):                    return "SceCtrlLatch *";
    case WC_(ARG_pspAudioInputParams_PTR):             return "pspAudioInputParams *";
//     case WC_(ARG_SceNetMallocStat_PTR):                return "SceNetMallocStat *";
    case WC_(ARG_in_addr_PTR):                         return "in_addr *";
    case WC_(ARG_CONST_in_addr_PTR):                   return "const in_addr *";
    case WC_(ARG_socklen_t):                           return "socklen_t";
    case WC_(ARG_socklen_t_PTR):                       return "socklen_t *";
    case WC_(ARG_sockaddr_PTR):                        return "sockaddr *";
    case WC_(ARG_CONST_sockaddr_PTR):                  return "const sockaddr *";
    case WC_(ARG_fd_set_PTR):                          return "fd_set *";
    case WC_(ARG_SceNetMallocStat_PTR):                return "SceNetMallocStat *";
    case WC_(ARG_msghdr_PTR):                          return "msghdr *";
    case WC_(ARG_CONST_msghdr_PTR):                    return "const msghdr *";
    case WC_(ARG_in_addr_t):                           return "in_addr_t";
    case WC_(ARG_sceNetApctlHandler):                  return "sceNetApctlHandler";
    case WC_(ARG_SceNetApctlInfo_PTR):                 return "SceNetApctlInfo *";
    case WC_(ARG_pdpStatStruct_PTR):                   return "pdpStatStruct *";
    case WC_(ARG_ptpStatStruct_PTR):                   return "ptpStatStruct *";
    case WC_(ARG_pspAdhocMatchingCallback):            return "pspAdhocMatchingCallback";
    case WC_(ARG_pspAdhocPoolStat_PTR):                return "pspAdhocPoolStat *";
    case WC_(ARG_productStruct_PTR):                   return "productStruct *";
    case WC_(ARG_sceNetAdhocctlHandler):               return "sceNetAdhocctlHandler";
    case WC_(ARG_SceNetAdhocctlParams_PTR):            return "SceNetAdhocctlParams *";
    case WC_(ARG_SceNetAdhocctlScanInfo_PTR):          return "SceNetAdhocctlScanInfo *";
    case WC_(ARG_SceNetAdhocctlPeerInfo_PTR):          return "SceNetAdhocctlPeerInfo *";
    case WC_(ARG_SceNetAdhocctlGameModeInfo_PTR):      return "SceNetAdhocctlGameModeInfo *";
    case WC_(ARG_pspTime_PTR):                         return "pspTime *";
    case WC_(ARG_CONST_pspTime_PTR):                   return "const pspTime *";
    case WC_(ARG_CONST_time_t):                        return "const time_t";
    case WC_(ARG_SceMpeg_PTR):                         return "SceMpeg *";
    case WC_(ARG_SceMpegStream_PTR):                   return "SceMpegStream *";
    case WC_(ARG_SceMpegAu_PTR):                       return "SceMpegAu *";
    case WC_(ARG_SceMpegRingbuffer_PTR):               return "SceMpegRingbuffer *";
    case WC_(ARG_SceMpeg):                             return "SceMpeg";
    case WC_(ARG_SceMpegAvcMode_PTR):                  return "SceMpegAvcMode *";
    case WC_(ARG_sceMpegRingbufferCB):                 return "sceMpegRingbufferCB";
    case WC_(ARG_SceMp3InitArg_PTR):                   return "SceMp3InitArg *";
    case WC_(ARG_PspHttpMethod):                       return "PspHttpMethod";
    case WC_(ARG_PspHttpMallocFunction):               return "PspHttpMallocFunction";
    case WC_(ARG_PspHttpFreeFunction):                 return "PspHttpFreeFunction";
    case WC_(ARG_PspHttpReallocFunction):              return "PspHttpReallocFunction";
    case WC_(ARG_PspHttpPasswordCB):                   return "PspHttpPasswordCB";
    case WC_(ARG_PspGeListArgs_PTR):                   return "PspGeListArgs *";
    case WC_(ARG_PspGeBreakParam_PTR):                 return "PspGeBreakParam *";
    case WC_(ARG_PspGeCallbackData_PTR):               return "PspGeCallbackData *";
    case WC_(ARG_PspGeContext_PTR):                    return "PspGeContext *";
    case WC_(ARG_CONST_PspGeContext_PTR):              return "const PspGeContext *";
    case WC_(ARG_PspGeStack_PTR):                      return "PspGeStack *";
    case WC_(ARG_pspUmdInfo_PTR):                      return "pspUmdInfo *";
    case WC_(ARG_pspUtilityNetConfData_PTR):           return "pspUtilityNetConfData *";
    case WC_(ARG_netData_PTR):                         return "netData *";
    case WC_(ARG_pspUtilityMsgDialogParams_PTR):       return "pspUtilityMsgDialogParams *";
    case WC_(ARG_SceUtilitySavedataParam_PTR):         return "SceUtilitySavedataParam *";
    case WC_(ARG_SceUtilityOskParams_PTR):             return "SceUtilityOskParams *";
    case WC_(ARG_pspUtilityGameSharingParams_PTR):     return "pspUtilityGameSharingParams *";
    case WC_(ARG_pspUtilityHtmlViewerParam_PTR):       return "pspUtilityHtmlViewerParam *";
    case WC_(ARG_PspBufferInfo_PTR):                   return "PspBufferInfo *";
    case WC_(ARG_PspOpenPSID_PTR):                     return "PspOpenPSID *";
    case WC_(ARG_SceKernelUtilsSha1Context_PTR):       return "SceKernelUtilsSha1Context *";
    case WC_(ARG_PspDebugPutChar):                     return "PspDebugPutChar";
    case WC_(ARG_SceModule_PTR):                       return "SceModule *";
    case WC_(ARG_PspIoDrv_PTR):                        return "PspIoDrv *";
    case WC_(ARG_SceKernelLoadExecVSHParam_PTR):       return "SceKernelLoadExecVSHParam *";
    case WC_(ARG_PspUsbCamSetupVideoParam_PTR):        return "PspUsbCamSetupVideoParam *";
    case WC_(ARG_PspUsbCamSetupVideoExParam_PTR):      return "PspUsbCamSetupVideoExParam *";
    case WC_(ARG_PspUsbCamSetupStillParam_PTR):        return "PspUsbCamSetupStillParam *";
    case WC_(ARG_PspUsbCamSetupStillExParam_PTR):      return "PspUsbCamSetupStillExParam *";
    case WC_(ARG_SceNetInetTimeval_PTR):               return "SceNetInetTimeval *";

    case WC_(ARG_VA_ARGS):        return "...";
    case WC_(ARG_UNKNOWN):        return "?";
    default:                      return "?!";
    }
}
